<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Document</title>
    <script>
        document.addEventListener("DOMContentLoaded",()=>{
            document.querySelector("h1")  
            //조건문으로 예외를 처리하는것을 기본적인 예외처리가 부름
            if(h1 === null){
                console.log("오류가 발생했습니다")
            }else{
                h1.textContent = "변경!"
            }
        })
    </script>
    <!-- 위와 같은 코드-->
    <script>
        //고급 예외객체 
       try{
        //예외가 발생할 가능성이 있는 코드
        h1.textContent = "변경!"
       }catch(error){
        //예외가 발생했을 때 실행할 코드
        console.log("오류가 발생했습니다")
       }finally{
        //무조건 적으로 실행
       }
    </script>
    <script>   
        const 예 = () =>{
            try{
            console.log("예외가 발생할 가능성이 있는 코드")
        }catch(e){
            console.log("예외가 발생할 때 실행할 코드")
        }finally{
            console.log("무조건 적으로 실행할 코드")
        }
        }
    </script>
    <script>
        const Perimeter = (r) => {
            if(r<0){
                throw "길이는 음수가 될 수 없습니다" //throw 강제로 예외를 발생시킴
            }
            const pi = 3.15
            return 2*pi*r 
        } //throw를 사용하면 프로그램이 강제 종료가 됨으로 뒷처리로 try,catch를 사용
        try{
            console.log(getPerimeter(-10))
        }catch(e){
            console.log("어떤 문제가 발생했습니다")
        }
        console.log("프로그램이 정상적으로 종료되었습니다")
    </script>
</head>
<body>
    
</body>
</html>